[toolchain]
package_manager = "yarn"
solana_version = "2.2.20"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solana_core_contracts = "DzSqpUpL8DJ1z3wNAFnPMKRPZQL1oEZrwwSnXkA4w8Ce"

[programs.localnet]
solana_core_contracts = "GjU1P2X665JX3kygXqYYttTncfUwwh1akDK2apV13GUf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn btc:start && NODE_OPTIONS='--import tsx' yarn run mocha --no-warnings --timeout 1000000 --exit 'tests/sign-respond-erc20.ts'; exitcode=$?; yarn btc:stop; exit $exitcode"
